code100x/cms

- src/app/globals.css
This PR fixes #21 
Reason for issue:
This issue occurs because of a conflict in CSS due to the use of the !important keyword. To resolve this, I removed the specific code as it was not necessary.
Issue:
Fix:
// @hkirat Please have a look at this PR.
> [BugFix] The video doesn't fill the screen in full-screen mode.

- src/components/Sidebar.tsx
> [Bugfix] Bonked Sidebar Colors in light mode

- src/app/page.tsx
- src/components/CourseCard.tsx
- src/components/Courses.tsx
- Course page paddings, description, etc.
- Course Card appearance
Desktop View:
Mobile View:
> fix: Course Page & Card

- src/actions/comment/index.ts
This should fix #104 
Just by reapproving the comment it should fix the previously approved segments
> fix segments parser supports hourly syntax

- src/components/Signin.tsx
I have added the check for ensuring email and password are non-emty/not-null. And in case they are null (if user didn't provide them), then added the logic to show error message below respected form fields to ask him for the same, and prevent him from moving ahead in such case.
Error message when fields are left blank.
Error goes away when user starts typing
> fix: able to login without credentials (signin field validation missing)

- .env.example
- pnpm-lock.yaml
- src/lib/auth.ts
This pr introduces simple role based access that can be improved further.
Role based access will allow us to improve the admin dashboard and render components/tags based on the role in the session.
How it works: 
Add `ADMINS` field in .env, like in the example: 
`ADMINS = "Random,example@gmail.com,..."`
on login it does check if the current user is included in the admin list
> Introducing simple role based access

- src/app/globals.css
This PR fixes the overlapping of timestamp by updating the CSS.
Fixes #145
Below video shows the fix:-
[Screencast from 2024-03-04 01-14-42.webm](https://github.com/code100x/cms/assets/95973239/d3ef85dd-f38f-418d-b7a9-a1efc40717ec)
> Overlapping Timestamp fix

- .github/workflows/lint.yml
Fixes : #172 
Fail the job if `lint:check` exits with a non-zero code
> fix-ci pipeline should fail on PR if lint fails - #172

- src/components/admin/ContentRendererClient.tsx
Fixes : #165  
By removing few extra br's we can fix this issue
And because , we are using this component at one place .. there is no need to cross check this component at other places
> --fix-too-much-space-b/w-video-and-comments

- src/db/Cache.ts
This pull request enhances the existing Cache utility by introducing the capability to set dynamic expiry times fvor each cache entry. Previously the cache expiry time was statically set, limiting the utility's flexibility. With this update, users can specify the expiry time in seconds for each set operation, allowing for more nuanced cache control tailored to specific need.
> Feature: Dynamic Cache Entry Expiry

- .gitignore
- docker-compose.yml
Fixes [#181](https://github.com/code100x/cms/issues/181)
`Error response from daemon: Mounts denied
The path /postgres-data is not shared from the host and is not known to Docker.`
Changing 
`    volumes:
- /postgres-data:/var/lib/postgresql/data
`
to 
`    volumes:
- ./postgres-data:/var/lib/postgresql/data
`
cms-docker: Error P1001: Can't reach database server at 'db':'5432'
Please make sure your database server is running at `db`:`5432`
- Add health check condition for db in `depends_on` to ensure docker-cms runs only after docker-db is up and ready.
- Add health check to postgres docker container
- https://www.warp.dev/terminus/docker-compose-depends-on
- https://github.com/peter-evans/docker-compose-healthcheck
> fix: docker compose up failing on localhost

- src/components/QualitySelectorControllBar.ts
- src/components/VideoPlayer2.tsx
- src/components/VideoPlayerSegment.tsx
- src/components/admin/ContentRendererClient.tsx
- src/db/Cache.ts
https://github.com/code100x/cms/assets/68022411/fb497736-9c72-478b-a1fb-0e94654a7f7b
Addresses issue #142 
Features:
1. the page doesn't reload whenever the video quality changes. Only the video URL gets changed. I added different videos to showcase that whenever quality changes, the video URL changes.
2. the video progress continues whenever quality changes, instead of starting from zero.
Note: I didn't change anything in the Cache.ts file; it is changed just because of a prettier check while committing.
> Only Videoplayer gets re-rendered when video quality is changed and the whole page doesn't get reloaded.

- package.json
- pnpm-lock.yaml
- src/components/landing/footer/footer.tsx
Updated all brand logos (X, Instagram, YouTube) to use Simple Icons, since Lucide Icons are planning to deprecate all their brand icons soon ([active PR here](https://github.com/lucide-icons/lucide/issues/94)).
Lucide's maintainers recommend switching to Simple Icons in [this discussion](https://github.com/lucide-icons/lucide/issues/670#issue-1236209233). 
Additionally also updates the Twitter logo to the new X logo as mentioned in #224.
- Lucide is planning to remove all brand logos from their icon pack as mentioned in this discussion ([link to discussion](https://github.com/lucide-icons/lucide/issues/670)).
- The recommended alternative according to the maintainers of Lucide is [Simple Icons](https://simpleicons.org/).
- Screenshot below showcases what the deprecation errors look like. …
> fix: Updated deprecated Lucide brand icons

- src/actions/refresh-db/index.ts
- src/components/Courses.tsx
- src/components/RefreshDb.tsx
- src/db/Cache.ts
- src/utiles/appx-check-mail.ts
- src/utiles/appx.ts
@hkirat make sure to test the code since I couldn't access appx api
Fixes #272
> fix: the edge case problem

- src/app/pdf/[contentId]/page.tsx
- src/components/Appbar.tsx
- src/components/NotionRenderer.tsx
- src/components/landing/footer/footer.tsx
- src/components/print/Print.tsx
- src/components/print/PrintNotes.tsx
- src/hooks/useMountStatus.ts
Had to modify css in the printing page for the printed document to look decent.
- Without css modifications: [Without Css Modifications.pdf](https://github.com/code100x/cms/files/14794983/Without.Css.Modifications.pdf)
[Screencast from 2024-03-29 01-40-41.webm](https://github.com/code100x/cms/assets/37402791/3c419dea-e49e-4d52-a460-c6e5a7b7cb2e)
- After Final Code: [After Final Code.pdf](https://github.com/code100x/cms/files/14795010/Final.Code.pdf)
[Screencast from 2024-03-29 01-39-18.webm](https://github.com/code100x/cms/assets/37402791/c84d9951-fc5a-462b-a3d6-3678a7f27cd0)
> feat: downloading notes

- src/components/Courses.tsx
- src/components/MyCourses.tsx
- src/components/RefreshDb.tsx
- src/components/VideoPlayer2.tsx
- 1 multiple instances of singleton
Resolves #279
> fixed multiple instances of singleton

- src/components/VideoPlayer2.tsx
- 1. This issue just needed to get the focus back to video after user toggle Fullscreen button.
- 2. It was quite irritating to click on the screen every time while changing tabs to control the video.
Resolves #262  
- [Y] I have performed a self-review of my code
- [Y] I assure there is no similar/duplicate pull request regarding same issue
Before Fixing the issue:
https://github.com/code100x/cms/assets/89627050/fe63294c-1227-47e4-9aeb-0023dbe4146b
After Fixing the issue:
https://github.com/code100x/cms/assets/89627050/ed0c4e82-0d1e-4d21-a69f-f87bba19483f
> [SOL]  Arrow keys don't work after toggling the Fullscreen unless clicked on the video again. #262

- src/components/BreadCrumbComponent.tsx
- src/components/CourseView.tsx
- src/components/VideoPlayer2.tsx
- src/components/ui/breadcrumb.tsx
Closes #282 : **Dynamic Breadcrumbs**
This PR adds breadcrumbs , which will show up above the course content. These breadcrumbs will change as users move around, showing exactly where they are in the course. Making it easy to see which part of the course you're in and navigate between sections by clicking, even if the sidebar is closed, for a better user experience.
Below is how it looks like : 
https://github.com/code100x/cms/assets/118182376/14ee3656-bbca-49d0-b696-13b61cf247c0
> Feat : Introducing Breadcrumbs for Enhanced Course Navigation and better UX.

- src/components/admin/ContentRendererClient.tsx
- Currently, the video refreshes when we click on `Mark as Complete/Incomplete` button.
Solution:
- The problem occurred because the `source` was updated repeatedly with state changes. I used useMemo() to cache it and now the `source` gets updated only when mpdUrl updates. And hence, the video doesn't get reloaded when clicking `Mark as Complete/Incomplete`
> fix: video refreshes after clicking on Mark as Complete/Incomplete

- prisma/seed.ts
- src/app/admin/layout.tsx
- src/lib/auth.ts
- src/middleware.ts
- Improves the seed command to not fail when executed once more
- Uses `process.env.LOCAL_CMS_PROVIDER` to provide mock users in middleware and signup
> fix(dev): improve local development experience

- .eslintrc
This fixes the minor issue where ESLint's styling rules were overwriting the Prettier styling rules. Videos below showcase an example.
This PR is part of the Turborepo monorepo migration mentioned in #234.
EDIT: Comment below in this PR ([here](https://github.com/code100x/cms/pull/244#issuecomment-2006243552)) showcases an example of the conflicting styling rules caused before this PR.
👇 Shows how the `lint:fix` script overrides changes done by `format:fix`
https://github.com/code100x/cms/assets/45622345/71cfdeb2-8e62-450a-8d5a-da72d12576d4
👇 ESLint (`lint:fix`) no longer conflicts with Prettier's (`format:fix`) styling changes now
https://github.com/code100x/cms/assets/45622345/ea8b2486-8556-4804-baf4-5acadb1b93f6
> fix: Fixed ESLint styling rules overriding Prettier styling rules

- src/components/WatchHistoryClient.tsx
- src/components/ui/carousel.tsx
- 1 Added left arrow to the carousel if canScrollPrevious.
- 2 Made css changes for mobile.
Resolves #305
> fixed: left arrow not visible on watch history carousel

- src/components/comment/CommentInputForm.tsx
- Fixing the issue of keybindings interference between the video player and comments.
Resolves #364 
This PR addresses an issue where keyboard shortcuts used in the comment textarea were affecting the video player's behavior. The problem occurred when certain keys, such as `<` or `>`, were pressed while typing comments, causing unintended effects on the video playback speed.
To resolve this issue, I added event handling to prevent the propagation of keyboard events when typing in the comment textarea. 
This change ensures that keyboard shortcuts are properly isolated to the comment input area, providing a smoother user experience without interfering with the video playback.
https://github.com/code100x/cms/assets/111479342/f526a7cd-b23a-4619-ab6f-086e913751d5
> Fix: Keybindings Interference Between Video Player and Comments

- src/actions/refresh-db/index.ts
- 1. Earlier, we were hitting checkUserEmailForPurchase in refresDb in both local and prod
- 2. Since in local we don't have APPX Creds, we now only hit it in production.
Resolves #402 
[Screencast from 14-04-24 11:47:05 AM IST.webm](https://github.com/code100x/cms/assets/130341088/91966eb1-c308-4459-8cd4-2f0ff38a5cb6)
[Screencast from 14-04-24 11:48:13 AM IST.webm](https://github.com/code100x/cms/assets/130341088/bc04ee74-f5ff-4973-8a42-320e08a5cd8a)
- I have performed a self-review of my code
- I assure there is no similar/duplicate pull request regarding same issue
> hit checkUserEmailForPurchase in refreshDB only in prod

- README.md
when setting up the project locally the prisma:migrate:dev is not present in package.json only prisma:mirgrate is present.
Resolves #[524]
> FIXING #524 ERROR

- src/components/search/SearchBar.tsx
Fixes issue in #511 . The request being sent was trimming the end trailing spaces. So, start checking by trimming the trailing spaces in the searchTerm on the page itself. 
- #511
Resolves #511  
- [Yes] I have performed a self-review of my code
- [Yes] I assure there is no similar/duplicate pull request regarding same issue
> Fix issue #511

- src/app/api/search/route.ts
- 1 Improves searchresult
- 2
https://www.fusejs.io/api/options.html#minmatchcharlength
Resolves #310
> chore: increase min char match length

- src/components/ContentCard.tsx
- Fixed the issue  by making text color of time duration white
Resolves #515
> fix: #515 add text colour to time duration

- package.json
There was an trailing comma, which was causing errors while running docker-compose up command, so this is just to remove it
> bug on running the docker-compose up

- prisma/migrations/20240601123949_added_migration_status/migration.sql
- prisma/schema.prisma
- tsconfig.json
Added Migration status to db for video migration
Resolves #745 
Complete Code for migration here: https://github.com/nimit9/code100x-videos
> added migration status to video metadata

- package-lock.json
- src/actions/refresh-db/index.ts
- src/app/api/search/route.ts
- src/db/Cache.ts
- src/db/course.ts
- src/utiles/appx.ts
- Improve Singleton implementation for Cache.
- Does it add any feature or fix any bug in the application ?  > **No.**
- Does it improve performance of the application ?  > **Probably not.**
- Does it improve code quality and maintainability ? > **Yes.** 
Resolves #777
> Chore | Singleton implementation for Cache

- src/components/admin/ContentRenderer.tsx
This PR adds a new feature to the `ContentRenderer` component that checks if the main video URLs from the database are accessible or not. If any of the main URLs are not accessible, it falls back to using the Bunny URLs instead.
Changes:
1. Added a new helper function `isUrlAccessible` that makes a HEAD request to a given URL and returns a boolean indicating whether the URL is accessible or not.
2. Modified the `getMetadata` function:
- If the `user.bunnyProxyEnabled` flag is true, it returns the Bunny URLs directly.
- If `bunnyProxyEnabled` is false, it creates an object `mainUrls` containing the main URLs from the database.
- It then uses `Promise.all` and the `isUrlAccessible` function to check if all the main URLs are accessible.
- If all main URLs are accessible, it returns …
> feat: Add fallback to Bunny URLs if main URLs are not accessible

- src/components/CardComponent.tsx
- src/components/Certificate.tsx
- src/components/ContentCard.tsx
- src/components/videothumbnail.tsx
- tsconfig.json
- 1 Introuduced the dynamic content generated (card component) so it changes the content inside based on the title of the  folder , video , notion accordingly.
- 2 To not to disturb the design of the previous static images I have designed the same card like template so it changes the content inside the card and also the icons will be dynamically changed.
Resolves #790 .
Here are the proofs of how this works and my design , I am providing both the screenshots as well as screencast so in screencast you can able to see the responsiveness of the card component
screenshot of how video and notion looks like
screenshot of how folder looks like
screencast of all together with mobile responsiveness has been shown here
[Screencast from 2024-06-16 …
> Dyanmic thumbnails generated according to the title of the video , notion , folder(current week)

- src/components/comment/TimeCodeComment.tsx
- 1 Fixes the word split at the end of comments box.
Before : 
After :
Resolves #801
> fixing word splits at the end of the comments card

- src/components/Signin.tsx
- Login button is now disabled when user hasn't entered his email and pass
Resolves #[[861](https://github.com/code100x/cms/issues/861)]
> fix: Signing in toaster without email and pass

- src/app/admin/page.tsx
- src/app/api/admin/discordReset/get/route.ts
- src/app/api/admin/discordReset/route.ts
- src/app/error.tsx
- tsconfig.json
**Fixes:**
**🔺There is no async-await for the submit request in form for discord reset**
**🔺Added toasts for proper informative messages**
**🔺Improved the UI of both forms & also made them mobile responsive**
Preview: https://github.com/user-attachments/assets/80581b86-dd48-4836-9d81-9904b66eb941
- [✅ ] I assure there is no similar/duplicate pull request regarding same issue
> Improved the UI for form & Fixed the Logic 

- src/app/error.tsx
- src/components/Copy-to-clipbord.tsx
- src/components/comment/CommentApproveForm.tsx
- src/components/comment/CommentDeleteForm.tsx
- src/components/comment/CommentPinForm.tsx
- tsconfig.json
- Fixed the issue where the pin functionality was partially working in the dropdown menu of individual comment.
Resolves #877
> fix: pin functionality issue in the comment dropdown menu

- src/components/search/SearchBar.tsx
- tsconfig.json
The search results are not fully visible as they are being blocked by course content due to incorrect z-index values.
- Increased z-index from `z-10` to `z-30` for search results
- The z-index of course content is `z-20`
> fix: Adjust z-index for improved search results visibility (#1082)

- src/components/Sidebar.tsx
- 1 Made the Content Sidebar Heading Sticky
Resolves #1084 
https://github.com/user-attachments/assets/319e3bdc-a0cb-4c53-858e-439453a17e74
> Made sidebar Header Sticky

- prisma/migrations/20240830223934_add_subtitle_tries/migration.sql
- prisma/schema.prisma
- src/actions/payoutMethods/schema.ts
- src/app/api/admin/services/subtitle/route.ts
- Added migration for subtitles service
- Added API routes for subtitles service
> Added subtitles service routes

- src/actions/videopreview/videoPreview.tsx
- src/components/videothumbnail.tsx
- 1 Course page will not leak the content
- 2 Stop unwanted multiple db calls made via server functions.
Resolves #1198
Context: We often think that the server function uses some sort of RPC call under the hood, but that's not the case. Next.js uses an HTTP call to serialize the data to the server. You can see this request(calling server function) in the network tab; the URL will be the same as the current path along with the header 'next-action': "<$7e6r763s34534f345w3434>". This key is associated with the server function, and you can find the function association in the .next folder.
Issue: There was feature which play the video content in the thumbnail which uses server function to get the video Metadata. that server function was unprotected. all I needed was a session with the server …
> fix: thumbnail-server-action

- src/app/globals.css
- src/components/QualitySelectorControllBar.ts
- 1 Items inside the quality selector in video controls is now visible in light mode
- 2 Remove unnecessary quotations
Resolves #1276 
Before:
After:
> fix: Quality selector bg issue in light mode

- src/app/api/admin/contentmetadata/route.ts
- src/app/api/admin/updatecontent/route.ts
- src/components/admin/UpdateVideoClient.tsx
- There are two api used update the videoMetadata :  ``` api/admin/updatecontent ``` and ``` api/admin/contentmetadata ```. rn anyone with or without logging can change or delete the videoMetadata based on content id. Added the admin-password check for the same.
Test: this was my api payload that cleared all the link from columns for endpoint :- contentmetadata 
```
{
"contentId" : 3,
"updates": {}
}
```
> Added authentication to content update apis.

- src/components/Signin.tsx
This pull request addresses issues with the email domain suggestions component:
- **Clear suggestions on mismatch**: If the user types a phone number or a custom domain that does not match the preset domains, the suggestions will disappear.
- **Hide suggestions on blur**: If the user doesn’t select a suggestion and clicks outside the input field, the suggestions will be cleared.
- 1 Updated `handleEmailChange` to clear suggestions for phone numbers and mismatched domains.
- 2 Added `onBlur` event handler to clear suggestions when the user clicks outside the input field.
Resolves #1211
> Issue: #1211

- src/components/Sidebar.tsx
- src/components/landing/landing-page.tsx
- 1 Fixes NavBar overlapping title on the Home page
- 2 Fixes course carousel getting cropped on zoomed screen
Resolves #1294
> fix: Main heading hidden behind navbar (#1294)

- src/components/CourseView.tsx
- src/components/Sidebar.tsx
- Fixed the issue where the video player was taking so much space that its part was being cut when on higher resolution
- For devices with a width greater than 1280px, the path and the button are on the same line.
- For all others, it's the same as it is.
- For 'xl' size and above, the CSS property changed to absolute and overlapped the button component.
- Made the z-index of button 50 to it to work.
- Tested in many scenarios.
_### Open for any other Suggestions or Changes_
Resolves #1180
> Fix new UI bug

- src/components/comment/Comments.tsx
This PR fixes the bug where any user could click on the 3 dots (options menu) for comments not authored by them. The 3 dots are now only visible to the comment's author. This ensures proper access control for comment actions.
Added a check to compare the logged-in user ID with the comment author ID before rendering the options menu.
Resolves #1259
- ✅ I have performed a self-review of my code
- ✅ I assure there is no similar/duplicate pull request regarding same issue
> Restrict 3 dots options menu to comment author

- src/components/Sidebar.tsx
- 1 bug: show content button hide the Breadcrumb #1389
Resolves #[ #1389]  #[#1380]
- [yes ] I have performed a self-review of my code
- [yes ] I assure there is no similar/duplicate pull request regarding same issue
> bug: show content button hide the Breadcrumb #1389

- src/actions/bookmark/types.ts
- src/components/CourseView.tsx
- src/components/bookmark/BookmarkList.tsx
- src/db/bookmark.ts
- 1 Added support for folder and notion doc
- 2 fix the bookmark state in the course view page. which was causing the bookmark button be active thus allowing the user to create same bookmark again polluting the db. 
Resolves #1231  
[Screencast from 15-09-24 09:52:22 PM IST.webm](https://github.com/user-attachments/assets/e9cebde8-597c-4c53-8811-14c7c2164776)
> fix bookmark and view of bookmark

- src/components/Sidebar.tsx
- Resolves the issue with longer titles in SideBar, by breaking the title instead of truncating it.
Resolves #1361
> Fixes: #1361  Breaking words instead of truncate for longer titles.

- src/components/profile-menu/ExternalLinks.tsx
- 1 Added separate cohort 2 and cohort 3 assignment links
#1367
> FIX: Add separate cohort 2 and cohort 3 assignment Links

- src/app/(main)/(pages)/home/page.tsx
- src/components/Navbar.tsx
- src/components/search/CommandMenu.tsx
- src/components/search/SearchBar.tsx
- src/components/search/SearchResults.tsx
- src/components/search/VideoSearchCard.tsx
- src/hooks/useDebounce.ts
- Add global search bar in `Navbar`
- Implement command menu for page navigation
- Create mobile-friendly search overlay
- Enhance user experience with quick access to content
- Improve accessibility with keyboard shortcuts
- Ensure consistent search functionality across devices
- Utilize debounce hook for optimized API calls
- Implement `CommandMenu` component for advanced search options
- Refactor `SearchBar` component for reusability
https://github.com/user-attachments/assets/a4994f31-ba12-40be-8a2b-d9c5c85db47a
https://github.com/user-attachments/assets/0698fdce-6c5c-49d1-b85e-0f5eb60959aa
> Implement global search functionality

- src/components/Navbar.tsx
This commit reintroduces the search functionality in the `Navbar` component 
that was inadvertently removed due to a merge conflict. The changes include:
- Re-added `SearchBar` component for desktop view
- Fixed Search button for mobile view
- Ensured search elements are only visible for authenticated users
- Resolves #1464 
@devsargam 
https://github.com/user-attachments/assets/a18afc91-6df0-42f2-b8c9-e3b4e0ab651f
> fix: Restore search functionality in Navbar component

- .env.example
- README.md
- setup.sh
-  This PR helps new developers run the project instantly.
- 1 Added a setup.sh file in the main file directory
- 2 Modified the .env.example so that setup.sh file works properly
- 3 Made huge changes to the  Readme file so that users can fork & run the project faster
Hey Sargam, firstly thanks for looking up on my PR. This is my first PR of life. Please feel free to scold me if my PR have any issue with respect to Open Source Contributing rules. I would love to improve & learn from you. 
Thanks for providing your valuable time & reviewing my PR.
> feat: Instant Project Online

- src/components/landing/footer.tsx
1. Fixes the typo in the SVG property from stroke-linecap to strokeLinecap, resolving the invalid DOM property warning.
Resolves #1491
> fix: typo fixed from stroke-linecap to strokeLinecap

- src/components/Sidebar.tsx
- 1 Fixes last item visibility in the accordion list, ensuring the bottom item is fully accessible above the bottom navigation bar.
- 2 Adjusts padding to prevent UI elements from being hidden behind the navigation bar.
Resolves #1544
> Fix: Ensure last accordion item is fully visible above bottom navigation

- src/components/BreadCrumbComponent.tsx
- src/components/Navbar.tsx
> FIX: Map keys error

- src/components/VideoPlayer2.tsx
The right arrow key stops functioning after being pressed three times.
[before.webm](https://github.com/user-attachments/assets/b4742406-5dca-4085-bb4e-ef6f0eb78b22)
[after.webm](https://github.com/user-attachments/assets/7286a271-d0ad-4a2b-afe7-874a052d681e)
> fix: resolve issue with right arrow keystroke functionality

- prisma/migrations/20241130091016_added_appx_video_id_mapping_with_appx_video_json/migration.sql
- prisma/schema.prisma
- src/actions/user/index.ts
- src/app/api/admin/content/route.ts
- src/components/AppxVideoPlayer.tsx
- src/components/CourseView.tsx
- src/components/FolderView.tsx
- src/components/VideoPlayer2.tsx
- src/components/VideoPlayerSegment.tsx
- src/components/admin/AddContent.tsx
- src/components/admin/ContentRenderer.tsx
- src/components/admin/ContentRendererClient.tsx
- src/db/course.ts
- src/lib/auth.ts
- src/utiles/appx.ts
> Fixed Appx Video, Added VideoJson Ref to VideoIds

- src/app/api/og/home/route.tsx
- src/config/site-config.ts
> feat: adds dynamic OG image

- src/components/Sidebar.tsx
- 1 Auto scroll to currently selected week in sidebar 
- 2 Closes sidebar when ESC is pressed
https://github.com/user-attachments/assets/8d19f820-daa5-4d54-9fc1-cac501ffa84c
Resolves #1530
> feature: auto scroll to the selected week in sidebar and closing sidebar on ESC

- .vscode/settings.json
- src/components/Appbar.tsx
- src/components/Sidebar.tsx
- Last sidebar element being overlapped by the footer menu on all devices (mobile, tablet, laptop)
- Improved sidebar responsiveness for large screen sizes
**Issue Description:**
1. The last element of the sidebar was always overlapped by the footer menu, causing usability issues. This problem occurred consistently across all screen sizes.
2. Navigation was not optimally responsive for 13-inch laptop screens.
**Fix Description:**
1. Applied a padding-bottom of `6rem` to the sidebar to ensure sufficient space for the last element to be visible above the footer menu.
2. Updated Tailwind responsive classes from `2xl` to `lg` in AppBar component
3. Increased the AppBar width from 12vw to 20vw to accommodate all navigation items on smaller screens
4. Implemented a more consistent navigation …
>  Resolve overlap issue of the last sidebar element with the footer menu across all devices

- src/app/globals.css
- src/components/Appbar.tsx
- Fixed app bar icon sizing by setting the min-width to 3.7rem (previously, the width was set to 4vw with no min-width), leading to  icons shrinking to an unusually small size.
- Increased padding in the wrapper to resolve the overlapping issue between the app bar and buttons.  
| **State**   | **Screenshot**          |  
|-------------|-------------------------|  
| **Before**  | <img width="1280" alt="Screenshot 2024-12-06 at 6 48 34 PM" src="https://github.com/user-attachments/assets/6a5327ba-3528-446a-84d1-eeefa6cddedb"> |  
| **After**   | <img width="1280" alt="Screenshot 2024-12-06 at 6 47 07 PM" src="https://github.com/user-attachments/assets/bb20e789-f5e7-4f4e-8422-fb717a02b326"> |  
@devsargam @siinghd
> Fix App Bar Icon Shrinking and Wrapper Overlapping with main contents Issues

- src/components/Sidebar.tsx
Fixed closing button of the sidebar.
Before:
After:
Changed CSS from `top-0` to `top-[64px]`... WHY 64PX??
**Explanation:**
In tailwind.config.js, we have defined height of the sidebar as `100vh-64px`:
https://github.com/code100x/cms/blob/204c49667b386c29cc9699180adce5775c5df7dc/tailwind.config.js#L87-L89
Similarly in tailwind.css:
https://github.com/code100x/cms/blob/204c49667b386c29cc9699180adce5775c5df7dc/src/styles/tailwind.css#L1053-L1055
But the sidebar had inline TailwindCSS in which we defined `top-0` so it was sticking to the top and was getting covered by navbar.
> minor: Fixed hidden closing button of Sidebar

- src/components/Appbar.tsx
- 1 EventListener added in appbar
> Event listener

- src/lib/auth.ts
- src/middleware.ts
fix: Enforce single-session login by invalidating previous JWTs on new login #1517
- 1 Generate Unique JWT Token on every login
- 2 invalidate previous JWTs upon a new login.
- 3 Ensure that only one active session exists per user.
Resolves #[1517] 
- [✅] I assure there is no similar/duplicate pull request regarding same issue
> fix: multiple login session bug #1517

- src/components/CourseView.tsx
- 1 Made the breadcrumb stick to the header while scrolling.
Resolves #1627 
- [✅ ] I assure there is no similar/duplicate pull request regarding same issue
screenshot
> fix#1627: remove unnecessary space between header and breadcrumb

- src/app/courses/[courseId]/layout.tsx
- src/components/AppxVideoPlayer.tsx
- src/components/Navbar.tsx
- src/components/Sidebar.tsx
- src/components/VideoPlayerSegment.tsx
- src/components/ui/accordion.tsx
**Resolves**: #1624 #1577
- Adjusted the iframe width, which was previously hardcoded, causing misalignment on larger screens. The iframe now has a responsive relative width and maintains an aspect ratio for proper positioning inside the video container.
- **Fixed an issue where the last accordion item was hidden due to a previous commit that shifted the sidebar to the bottom by a few pixels.** Increased the padding-bottom of the sidebar to resolve this and made the text alignment of the accordion items left-aligned to ensure a coherent appearance on smaller devices.
---
| **Screen Size** | **Before**                                                                                                 | **After** …
> fix: iframe-video positioning and width fixes along with some accordion styling fixes 

- src/components/search/SearchBar.tsx
- Fixed vertical misalignment of the "Ctrl + K" icon inside the search bar.  
Resolves #1703   
---
> Bug-fix: Vertical misalignment of "Ctrl + K" icon inside the search bar #1703

- src/components/FolderView.tsx
- 1 A short and simple message displayed when filtered content is null to make a better user experience.
- 2 Displays different message for different filter.
Resolves #1725
> Added appropriate message for filter #1725
