CONTRIBUTING.md
README.md

This pull request creates a CONTRIBUTING.md file which has some guidelines for contributing.

doc: Add Contributing Guidelines

---

src/components/VideoPlayer2.tsx

Resolves issue #43 and also adds some extra functionalities for volume.
Added functionalities:
Press `Shift+,` to decrease playback speed.
Press `Shift+.` to increase playback speed.
Press `Shift+ArrowUp` to increase volume.
Press `Shift+ArrowDown` to decrease volume.
https://github.com/code100x/cms/assets/68022411/d03fb30e-ed82-43b8-8c11-1f4a9a194c70

Added keyboard functionalities of playback speed and volume control to video

---

src/components/Signin.tsx

Updated the login responsive

---

src/components/landing/footer/footer.tsx

- Fixed the no hover animation on Socials in the footer of the page 
https://github.com/code100x/cms/assets/49952404/904872a7-4c7f-4427-9273-a611079dda40

fix:socialhover in footer

---

package.json

Issue: https://github.com/vercel/next.js/issues/60301
The error is with the latest version of sharp, i have removed it, it is not needed and should be already present on vercel servers.

Fix deploy error

---

src/app/globals.css
src/components/Sidebar.tsx
yarn.lock

Fixes #92 . SIdebar will scroll individually.
https://github.com/code100x/cms/assets/72003665/d2658cc8-2eff-4aae-b85f-4e407a844fec

Fixes #92 : Side scroll individually and hidden scrollbar

---

src/app/(marketing)/layout.tsx
src/app/page.tsx

Resolve the overflow card problem on the homepage as discussed earlier. 
Details: https://github.com/code100x/cms/pull/106#issuecomment-1962869679
Issue: #112
https://www.loom.com/share/561b2b88fa8a4e77922c05eb82341969?sid=4140506c-5301-48ce-9eba-c9f4ef5eb5b5

fix Overflow course card inssue on Homepage

---

prisma/migrations/20240226220845_add_token_to_user/migration.sql

@siinghd missed to commit a migration from prisma
This pr fixes #119

fix: add missed migration by hshingh

---

src/components/comment/Comments.tsx

- Fixes : Issue #131 for scrollable comment section
https://github.com/code100x/cms/assets/160803937/da394df1-9519-4bab-8d8e-fb2e1cdd2684

Feat: Scrollable Comment Section 

---

src/app/admin/page.tsx
src/components/ui/textarea.tsx
yarn.lock

Made changes in the Admin UI related to the issue #108 
Dark Theme:
Light Theme:

fix: Enhance Admin UI

---

src/components/VideoContentChapters.tsx

Added the light mode changes

---

src/components/ThemeToggler.tsx
yarn.lock

This PR fixes the Theme settings overlap with notes 
Fixes #150 
Before:-
After fix:-

Theme overlap with notes fixed

---

src/components/NotionRenderer.tsx

This issue fixes the notionrenderer component overlapping the navbar. I have added before and after videos for better clarity
Before -
https://github.com/code100x/cms/assets/42664767/55ad5d95-9194-4bb5-8079-4ae34a4e2e7d
After - 
https://github.com/code100x/cms/assets/42664767/4e3b58e3-708e-490c-9563-197564e80259

added z index to fix navbar overlap

---

src/components/VideoPlayer2.tsx

fix: video player being responsive in all sizes (#144)

---

src/components/landing/appbar/nav-menu.tsx

There was a issue with   colour of join now in light mode so i have fixed it
BEFORE
AFTER

issues with light mode fixed

---

src/components/Sidebar.tsx

This PR addresses the issue of inconsistent text alignment in the sidebar by ensuring that all text items are uniformly aligned in left for all the devices.
Fixes #156 
Below image shows the sidebar Fix(All devices):-

Inconsistent Text Alignment in Sidebar(Mobile) Fix

---

src/db/course.ts
src/utiles/appx.ts

The issue i am facing was .. even i have completed all the videos .. the course card complete percentage is showing incorrect 
here is the video 
https://github.com/code100x/cms/assets/73944177/fb90c273-a34c-48b7-bdcb-fdd85814ad4b
After digging little bit , i got to know that because of some hidden videos .. we are facing this issue ..
so i reproduced the issue , by adding some test data on my local .. and my guess was right , so if fixed the issue instantly
and here are the ss of before and after 
Before
After
ps--
inside the course for folder percentage is correct because we are using different logic for creating content

fixed-the-percentage-count-issue-in-course-card-component

---

src/utiles/jsx.d.ts

fix: resolve JSX type warning

---

src/components/Sidebar.tsx

fix: overflow issue #167

---

src/components/comment/CommentInputForm.tsx

Change the visibility of comment box in light mode

---

src/app/api/user/route.ts

added a null check for token on user endpoint #194

fix #194: null check for token on user endpoint

---

src/components/VideoContentChapters.tsx

Fixes [#177](https://github.com/code100x/cms/issues/177) & dup. issue #189 
This PR addresses a visibility issue where the text and background colors of the current chapter are the same, causing difficulties in reading and distinguishing the content. 
To improve accessibility and readability, this PR updates the color scheme to ensure a sufficient contrast between the text and background. 
By making this change, we aim to enhance the overall user experience and make the content more accessible to all users.

ui-fix: Visibility issue for highlighted chapter in Light mode

---

src/utiles/appx.ts

Fixes #195
- Added use of the Cache class in the purchase API

#195 Used cache in the API calls

---

src/app/admin/layout.tsx
src/db/Cache.ts
yarn.lock

Extends #154 
Now only admins are able to view /admin/* routes

feat: setup admin routes to be admin only

---

src/components/VideoPlayer2.tsx

Holding key T will play video at 2x speed. Releasing the key will make the playback speed back to normal.

feat/ holding key T will run video at 2x

---

src/components/Appbar.tsx
src/components/landing/appbar/nav-menu.tsx
src/db/Cache.ts

with ref to issue 
#210 adding slides option

appbar modified

---

package-lock.json
src/utiles/appx.ts
yarn.lock

fix: cources from db

---

src/components/VideoPlayer2.tsx

This pull request introduces enhanced keyboard navigation functionality to the video player component, improving user interaction and accessibility. The following features have been added:
- 'R' key restarts playback from the beginning.
- 'M' key toggles mute/unmute functionality.
- 'K' key toggles play/pause functionality.
- 'J' key seeks backward by 10 seconds multiplied by the playback rate.
- 'L' key seeks forward by 10 seconds multiplied by the playback rate.
Closes #273

Improve keyboard navigation functionality to video player component

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/pull_request_template.md

feat: setup issue & pr template

---

src/components/VideoPlayer2.tsx
src/components/comment/TimeCodeComment.tsx

- Implemented a regular expression to match URLs within the comment text
- Opens the URLs in a new tab
Resolves #126

feat: Added Comments with Hyperlinks

---

src/app/invalidsession/page.tsx
src/components/Signin.tsx
src/components/VideoPlayer2.tsx

-  Now taosted will closed onclick of close button.
same but was there in file src\app\invalidsession\page.tsx, also updated it. 
Resolves #299

added dismiss method sonner toast to close it on click

---

src/components/VideoPlayer2.tsx

This Pull Request is to enable the toggle feature for subtitles
- Toggle feature for subtitles (currently for English).
Resolves #[#297]

feat: add subtitle toggle like yt

---

src/components/ContentCard.tsx
src/components/CourseCard.tsx
src/components/FolderView.tsx
src/components/Sidebar.tsx
src/components/VideoPlayer.tsx
src/components/VideoPlayer2.tsx
src/components/bookmark/BookmarkView.tsx
src/components/landing/us-section/why-us-card/why-us-content.ts
src/db/course.ts
src/lib/utils.ts
yarn.lock

- 1 Added the total video duration on the thumbnail 
- So that Just to check video duration we don't need to start every video (or check mobile app for)
Resolves #329
- Added duration

Video duration added on thumbnail (as seen in youtube)

---

docker-compose.yml
package.json

- 1 Updated the docker-compose file with 5555 port for routing on the app container
- 2 Added studio script with in the dev:docker script, so that studio runs when the container starts to run.
- 3 Added studio:docker script so that new window opens and shows the db content.
Resolves #398
[Screencast from 13-04-24 11:41:56 AM IST.webm](https://github.com/code100x/cms/assets/130341088/c50b233b-4797-4bb5-8ea8-e109940e0304)
-  I have performed a self-review of my code
-  I assure there is no similar/duplicate pull request regarding same issue

Fix studio command when running the project with docker.

---

.github/workflows/lint.yml
README.md
src/components/CourseCard.tsx
src/components/Sidebar.tsx
src/components/VideoPlayer.tsx
src/components/VideoPlayer2.tsx
src/components/bookmark/BookmarkView.tsx
src/components/landing/us-section/why-us-card/why-us-content.ts
src/db/course.ts
src/lib/utils.ts

- `npm run lint:fix` and `npm run format:fix` in ci have been changed to `npm run lint:check` and `npm run format:check`
- Now the ci will fail if the code is unformatted
- Improved the ci to work on different PR types
- Formatted the unformatted code in the main repo in this PR
Resolves #350

ci: improve ci

---

package.json
src/app/globals.css
src/components/VideoPlayerSegment.tsx
src/components/admin/ContentRendererClient.tsx
yarn.lock

- 1 Added margin between "Slides" and "View all chapters" button
- 2 Removed unnecessary <br> and added margins for better spacing
Resolves #418

fix margins between slides and view all chapters button

---

package.json
src/components/comment/CommentInputForm.tsx
src/components/print/Print.tsx

downloading notes now working

---

package.json
src/components/VideoPlayer2.tsx
src/components/YoutubeRenderer.tsx

- 1 Added Support for Youtube Videos.
- 2 Added Youtube Renderer Component in VideoPlayer
Resolves #435 
[Screencast from 18-04-24 07:11:10 PM IST.webm](https://github.com/code100x/cms/assets/130341088/764af490-67ad-4436-9ed0-9f5ee5ed5f88)
- I have performed a self-review of my code
- I assure there is no similar/duplicate pull request regarding same issue

feat: add Youtube Renderer in VideoPlayer

---

package.json
src/components/Signin.tsx

fix: Login Page Password Visibility Toggle Alignment Issue

---

src/components/Sidebar.tsx
tailwind.config.js

Resolves #472 
https://github.com/code100x/cms/assets/73058928/b84243ef-3a95-429d-b43e-890042b2b046

fix: sidebar update for mobile ux

---

package.json
src/app/layout.tsx

- Added Navbar loader in CMS
https://github.com/code100x/cms/assets/22127725/814421b4-3688-4c5d-930e-933711860e82
Resolves : Added Navbar loader in CMS which was discussed in live stream.

feat: added navbar loader

---

src/app/api/admin/course/route.ts
src/app/api/admin/discord/refresh/route.ts
src/app/api/admin/discord/route.ts
src/app/api/admin/drm/route.ts
src/app/api/admin/segments/route.ts
src/app/api/course/videoProgress/markAsCompleted/route.ts
src/app/api/course/videoProgress/route.ts

- 1 This PR adds validations for request inputs on the backend API routes wherever it was needed.
- 2 Also fixes some wrong status codes in some routes (440 was being used instead of 404).
Resolves #484  
@hkirat Those big differences in files changed is just because zod schemas were created there

Added request input validation on API routes

---

Dockerfile

-  Fix npm install error caused due to the canvas package 
Resolves #542 
-  I have performed a self-review of my code
-  I assure there is no similar/duplicate pull request regarding same issue

update docker file fixing error in 'RUN npm install' caused by canvas package

---

Dockerfile

Revert "update docker file fixing error in 'RUN npm install' caused by canvas package"

---

src/actions/comment/index.ts

- 1 Fixed bug #510 
Resolves #510

Fixed bug #510

---

src/components/ThemeToggler.tsx

- 1 There is only one file change, I have improved the toggler to change theme without asking you through a dropdown
Here is the video representation:
[Screencast from 30-04-24 03:57:16 PM IST.webm](https://github.com/code100x/cms/assets/129188028/856f637e-d560-4d2c-87db-0b937ed8a2fa)

theme toggler simplified

---

src/app/admin/user/LogoutUser.tsx
src/app/not-found.tsx
tsconfig.json

- 1.This PR fixes the Text , buttons visibility in 404 page not found page.
- 2 .This PR also introduced INHOUSE Error page with clean UI and also a button to go back to home page ("/") route.
- 3.This PR also solved the issue with the appropriate error messages not displaying.
Resolves #552 and  #555 
- I have provided the  Screen recording of that 404 page  before updating by visiting app.100xdevs.com page and after Updating in my local system.
[Screen Recording Click Here](https://drive.google.com/file/d/1Evc3BRJgsihDgac1ZGItQ7hOiYnm5dk6/view?usp=sharing)
/home/kethesainikhil/Pictures/Screenshots/Screenshot from 2024-05-09 10-45-52.png

InHouse Error Page Introuduced

---

docker-compose.yml
next.config.js

- hot reload problem on windows
Resolves #535

fixed docker hot reaload on windows

---

package.json
src/components/VideoPlayer2.tsx

https://github.com/code100x/cms/assets/134690552/976b8ee2-28ab-43ef-819f-8130fe6353c7

shortcut key for increasing/decreasing vol

---

src/components/MyCourses.tsx
src/components/landing/landing-page.tsx

- 1 Fixed the issue with the ChevronRight(icon) color in Light theme
Resolves #504  
https://github.com/code100x/cms/assets/88739731/dd9cf7a3-0dc7-4897-94d4-64698423bbbd

Adjusted ChevronRight(icon) color based on theme on landing-page

---

src/components/Sidebar.tsx
tailwind.config.js

Reverts code100x/cms#474
change in tailwind.config.js creates many problems -> landing page photos are not render and  UI layout is broken.

Revert "fix: sidebar update for mobile ux"

---

package.json
src/components/RefreshDb.tsx

- 1 Removed session log visible on console
Resolves #450

removed session log from console

---

src/app/history/loading.tsx

- 1 Fixed watch history skeleton
Resolves #306 
[Screen Recording](https://github.com/code100x/cms/assets/37402791/9c852d89-3a70-4559-b98d-ce1ac60ef67b)

fix: skeleton for history page

---

package.json
src/app/api/course/videoProgress/route.ts
src/components/CourseCard.tsx
tsconfig.json

- 1 video progress bug fix
Resolves #681

video progress bug fix

---

package.json
src/components/Appbar.tsx
src/components/CourseCard.tsx

- 1 #632 
Resolves #632 
Check discussion #633

fix/632 appbar fixes, hide join now and login button while loading

---

src/app/not-found.tsx

- 1Redirect to Home when you go to any notlisted routes
- 2Previously the routing is not up to the mark as it was created by me only so I fixed the error and appologize for not taking care of routing.
Below is the screen recording of before and after this pull request
[Screencast from 2024-05-14 11-44-10.webm](https://github.com/code100x/cms/assets/70809367/52e7e894-ef4a-4647-9eda-3d492bf2b3d6)

redirect to home fixed from InHouseError page

---

prisma/migrations/20240601213343_/migration.sql
tsconfig.json

Migrated prisma

---

src/components/CourseView.tsx
src/components/comment/Comments.tsx
src/components/comment/TimeCodeComment.tsx

- 1 Fixed error while clicking on replying button in comments.
- 2 Fixed error while clicking on timestamp in comments.
- 3 Fixed error while clicking on go back button from reply in comments.
Resolves #587 #602 #700 #712 #714 #715 #750 
OLD
[replyError.webm](https://github.com/code100x/cms/assets/28997328/d516763b-ed58-4374-949d-a6fcf3f7b618)
NEW
[replyErrorNew.webm](https://github.com/code100x/cms/assets/28997328/88f68c61-8dde-4c9d-aaf3-8e5a94f7d9a0)

Fix: Error while replying to comments + clicking on timestamp + going back from reply

---

src/components/Certificate.tsx
src/components/admin/ContentRenderer.tsx
src/components/comment/CommentApproveForm.tsx
src/components/comment/CommentDeleteForm.tsx
src/components/comment/CommentInputForm.tsx
src/components/comment/CommentPinForm.tsx
src/components/comment/CommentVoteForm.tsx
tsconfig.json

- 1  fix the multiple comments if you click the comment button quickly
- 2 Solved merged conflict error, which already present in the code-base

 fixed the multiple comments error if you click the comment button quickly

---

src/app/globals.css
tsconfig.json

- 1 Decreased the width of controls on small screen 
- 2 Removed Divider and Duration From the Control Bar
Resolves #754 
Screenshots or GIFs

Control Bar Out Of Bounds On Small Screen

---

README.md

- 1fixes the wrong docker command in read me
-
- [x ] I have performed a self-review of my code
- [ x] I assure there is no similar/duplicate pull request regarding same issue

Update README.md fixes the wrong docker command in read me

---

src/app/courses/[courseId]/layout.tsx
src/components/Sidebar.tsx
src/db/course.ts
src/utiles/appx.ts

On Opening Sidebar on Small Mobile Screens :
- 1 Folder View Getting Compressed 
- 2 Video Player Getting Compressed

Fix : Folder View And Video Player Getting Compressed

---

src/components/Certificate.tsx
tsconfig.json

- 1 Waits for Certificate to first generate and only then downloads the Certificate
- 2 displays Generating while certificate is being generated
https://github.com/code100x/cms/assets/136328410/fa0f96b8-eb5d-4763-b1c6-986c0f8b7d92
Resolves #764

Fix/ certificate download Bug

---

src/actions/refresh-db/index.ts
src/components/comment/CommentInputForm.tsx
src/utiles/appx-check-mail.ts

Resolves #409 
Changes done as requested by @hkirat in the branch typeError. Please review

Fixed src/actions/refresh-db/index.ts

---

src/components/VideoPlayer2.tsx

- The default click alt + number should only change the browser tabs. 
- Both the tab switch and the videoplayer seek to the respective number percentage was happening
- Try to play a video in app.100xdevs.com
- Try clicking alt + n ( where n is the index of a tab in your browser )
- This will automatically seek the video to the (n*10)%
- Which should only happen when n pressed alone without any modifier keys

Fixed modifier action propogation

---

src/components/Sidebar.tsx

- When navigating to video/notes from different weeks, the focus should be on the week whose content is currently being viewed.
Resolves #752

ContentID correction

---

prisma/migrations/20240811175241_add_payout_methods/migration.sql
prisma/schema.prisma
src/actions/payoutMethods/index.ts
src/actions/payoutMethods/schema.ts
src/actions/payoutMethods/types.ts
src/app/payout-methods/page.tsx
src/components/NewPayoutDialog.tsx
src/components/profile-menu/ProfileDropdown.tsx
yarn.lock

-  Added payout methods section
- User can add their upi and solana addresses
- Validation of upi and solana address format using regex
- Success and error messages
- Only 2 upi and 2 solana addresses can be added for a user
- Avoided duplicate values
- User can delete a particular address
- Cross device compatability
Resolves #873
[Take-your-development-skills-from-0-to-100-and-join-the-100xdevs-community.webm](https://github.com/user-attachments/assets/e90d2b44-dcb5-4fea-8a43-b6f78453b3dd)

feat: added payout methods section

---

src/components/Signin.tsx

minor ui-changes

---

src/components/sidebar/index.tsx

Added Refresh Button 
- Fixes issue #1016

Added RefreshDB button

---

src/components/RefreshDb.tsx
src/components/sidebar/index.tsx

fix: Fixed Refresh DB CTA in the sidebar

---

src/actions/payoutMethods/schema.ts
src/app/questions/[slug]/@question/page.tsx
src/app/questions/page.tsx
src/components/NewPostDialog.tsx
src/components/posts/PostCard.tsx
src/components/search.tsx

- 1 Questions Page
- 2  Single Question Page
- 3 MarkDown editor on reply
- 4  Content and Title fit
https://github.com/user-attachments/assets/4a1be849-1777-4266-9d8b-9a24e143eece
Resolves #946  and Resolves #935

fix: questions Page, single question page, reply MDeditor

---

src/components/Sidebar.tsx
src/components/VideoContentChapters.tsx
src/components/admin/ContentRendererClient.tsx
tsconfig.json

- 1 Makes the Video and Video-Chapters Responsive
Resolves #1033 
https://github.com/user-attachments/assets/b37b20a8-b996-401f-9959-db36b20561e0

Made video-player and video-chapters responsive

---

src/app/api/search/route.ts
tsconfig.json

fixed:search api req type

---

src/components/QualitySelectorControllBar.ts

- 1 Closing of drop up menu for quality selection in video player when option is clicked.
https://github.com/user-attachments/assets/5a058b7b-69ef-4b99-be7a-88b159657246

Bugfix : for video player drop up display

---

src/components/print/PrintNotes.tsx

Fixed https://github.com/code100x/cms/issues/1050

Disabled header in NotionRenderer.tsx

---

src/app/(main)/(pages)/layout.tsx
src/components/CourseCard.tsx
src/db/bookmark.ts

- 1 fix bookmark security issue
[Screencast from 10-09-24 01:27:44 AM IST.webm](https://github.com/user-attachments/assets/63c27551-28db-48b6-aa7a-f9901688ddad)

fix:bookmark

---

src/components/Appbar.tsx

-fix Menu bar UI
Resolves #1219

Fix Menu bar UI

---

.github/workflows/cd.yml
.github/workflows/cd_prod.yml
.github/workflows/lint.yml

Added staging and prod CI/CD pipeline

Added CI/CD workflow for staging and prod

---

src/components/Signin.tsx

1-the dropdown should disappears as the user clicks somewhere else on the page
Resolves #1304

dropdown should disappears as clicked somewhere else on the page

---

README.md

fixed issue-#1193: repeating commands in README.md

---

src/app/payout-methods/page.tsx

- 1 Fixed the UI of payout-method page for both mobile and desktop site
Resolves #1214
- [✅ ] I have performed a self-review of my code
- [✅ ] I assure there is no similar/duplicate pull request regarding same issue

UI Fixes in payout-methods

---

src/components/comment/Comments.tsx

- 1 On big comments the UI overflows making a weird horizontal flow.
Resolves #1206 
- [✅] I assure there is no similar/duplicate pull request regarding same issue

[BUG] fix comments overflow

---

src/app/(main)/(pages)/home/page.tsx
src/components/Greeting.tsx

#1182 Issue Fixed: 
- 1 I have fixed the issue while showing greeting in the home page.
The issue was related to the Server Side Rendering and I know the concept of it and I have refactored the code of greeting into Greeting component and marked it as client component and issue is solved.
This is my first contribution Thanks!

fix: Greeting in the home page

---

src/components/Sidebar.tsx

- 1  Sidebar now closes automatically when clicked outside.
[Screencast from 2024-09-11 11-42-57.webm](https://github.com/user-attachments/assets/af63d72a-deed-4c97-95d0-e8d22f09114b)
Resolves #1183

fix: Sidebar is not closing when clicking outside #1183

---

src/app/globals.css

fix: Smooth Custom Scrollbar

---

src/components/Signin.tsx

- 1 1 Handles sigin errors better with toasts
Resolves #[#1225 ]

Added error handling

---

src/components/posts/PostCard.tsx

- 1 Question card will show an pulse animation ( loading ) when clicked . 
Resolves #[1264]

Loading animation added when clicked on question card. Fix issue #1264

---

src/app/layout.tsx

feat:added top loader

---

docker-compose.yml

- 1 Project not running locally while using docker composer
Resolves #1293  
- [*] I have performed a self-review of my code
- [*] I assure there is no similar/duplicate pull request regarding same issue

bugfix: docker-compose up fails

---

src/components/NewPostDialog.tsx
src/components/posts/form/form-input.tsx

- 1  : Now, when user adds tags ( while adding New Questions ), added tags will be displayed 
- 2 : User can delete the added tags
Resolves #1239 
https://github.com/user-attachments/assets/c924ed31-0ed4-47c9-8d06-b254619de046

feat : list All User-Added Tags Before Submission

---

README.md

- 1 Improved README for clarity and usability.
- 2 Added step-by-step installation instructions and highlighted manual setup as the recommended method.
Resolves #1328

Improved README for clarity and usability.

---

src/components/comment/CommentVoteForm.tsx

- 1  #1320
- 2  #1322
Resolves  #1322  #1320

refactor(comment): improve voting functionality

---

src/components/VideoPlayer2.tsx

- Implements Picture-in-Picture (PiP) mode for the video player
- Introduces `P` key shortcut for quick PiP mode toggle
- Expands playback rate options to include 2.5x and 3x speeds
Resolves #1295 
https://github.com/user-attachments/assets/135bfa2c-7bfc-40aa-a1e0-f23c2e20ca07

fix: Add Picture-in-Picture functionality to video player

---

src/components/ContentCard.tsx

-  Fixed the issue where cards were not selectable using the keyboard.
Resolves #1360

fixed card selection using keyboard

---

src/components/ThemeToggler.tsx
src/components/profile-menu/ProfileDropdown.tsx

- Theme switcher and Profile Dropdown that is in Nav bar keyboard accessible
Resolves #1351

Fix navbar icons

---

src/components/bookmark/BookmarkButton.tsx
src/components/ui/sidebar-items.tsx

- focus issue for navbar anchor items with tooltip
- fixed bookmark icon focus & hover look
Before : 
https://github.com/user-attachments/assets/6794bd57-470c-4bbf-9bfc-6480cd4442ed
After : 
https://github.com/user-attachments/assets/1d8b9a35-63d0-434d-ae57-0ee1fee02f68
Resolves #1354

Fix sidebar items

---

README.md
src/components/CourseCard.tsx

- fixed anchor tags inside a button elements on home page. The issue in the sidebar seems to be a part of the TooltipTrigger being used from the UI library "@radix-ui/react-tooltip"
Resolves #1354
files updated: src/components/CourseCard.txt
README: added the prisma client generation step.
- [*] I have performed a self-review of my code
- [*] I assure there is no similar/duplicate pull request regarding same issue

Fixed: #1354, fixed anchor tags inside a button on home page

---

.github/workflows/lint.yml

- ci fails because pnpm cannot be found
- needs to be installed
Resolves #1338

ci: install pnpm

---

src/components/Sidebar.tsx

- 1 Hide Contents can now close the sidebar properly
Resolves #1403
https://github.com/user-attachments/assets/025e88f8-2971-4780-b080-08bde446194d

Fix: sidebar toggle functionality from button click (#1403)

---

src/app/api/search/route.ts
src/app/courses/[courseId]/layout.tsx

Revert "feat/search: Added search bar and other minor ui fix"

---

src/actions/commentVote/index.ts
src/actions/commentVote/schema.ts
src/components/Sidebar.tsx
src/components/posts/PostCard.tsx
src/components/posts/form/form-vote.tsx

- 1  Fixes re-rendering of whole page when question is voted on /questions
- 2  Fixes re-rendering of page when Editor is clicked
- 3  Fixes re-rendering of page when reply is added
Resolves #[1247] #1248 
Before:
https://github.com/user-attachments/assets/3a1cf56d-0fb9-46f3-b66b-70ea69845fe4
Before:
https://github.com/user-attachments/assets/34f5022a-4755-4b56-8433-9eb2a0f087e1
After:
https://github.com/user-attachments/assets/eb80c251-94ea-4c20-9a34-76b44205909c
After:
https://github.com/user-attachments/assets/ca687062-f258-4720-8abe-94f2e577a2cd

Fixed bugs of voting, editor clicks, replies

---

.github/workflows/lint.yml
.npmrc
src/app/(main)/(pages)/watch-history/page.tsx

- fixed the watch history bug where video is not playing through watch history
- also fixed lint.yml file
Resolves #1418
[fixed bug video](https://github.com/user-attachments/assets/74368c72-bb8d-4885-aff7-f181ee646c12)

fixed watch history bug and lint.yml

---

src/app/layout.tsx

Fix Hydration Mismatch in Layout Component
Description
This PR addresses the hydration mismatch warnings occurring due to class and style attributes being inconsistent between server and client renders.
Changes Made
Added suppressHydrationWarning={true} to the <html> and <body> tags
Ensured consistent class naming using the cn utility function
Fixed console warnings about extra class/style attributes
Problem Being Solved
The application was experiencing hydration mismatches between server-side rendered content and client-side React components, causing console warnings and potential rendering inconsistencies.
Screenshots
Before 
After

fix: resolve hydration mismatch in layout component

---

src/components/posts/tag.tsx
src/hooks/useColorGenerator.ts

Added aria labels for better accessibilty, Light House score improved 
Screenshot attached
@devsargam

FEAT: Imporve the Accessibilty and Visibility of Question Tags

---

src/app/api/user/exists/route.ts

- 1 Adds an endpoint to sync job board 
- 2 Needs an SECRET / API KEY 

feat: added endpoint to access / sync users into job board

---

src/components/comment/CommentInputForm.tsx
tsconfig.json

- added checks so that the blank comments are prevented from being added to the comment section.
Resolves #1440

Added checks so that comments are not blank.

---

src/components/posts/PostCard.tsx

Added a shadow to the PostCard component, so that the card has visible defined boundary in light theme.
- 1 - Added some shadow to the PostCard component, for a better visibility in light theme.

Added a shadow to the PostCard component.

---

src/components/ContentCard.tsx
src/components/FolderView.tsx
src/lib/utils.ts

- 1 Now we are able to see content title on hover of weekly course cards 
- 2 Some type fixes
Resolves #[1312] 
https://github.com/user-attachments/assets/34a0d777-5c71-43d6-882b-67a7dab1d51f

show content titles on hover of weekly cards

---

src/components/Signin.tsx

- 1 Fixed the responsiveness of login card
Resolves #[1477] 
https://github.com/user-attachments/assets/3d234429-eb89-4b0f-b07c-e9be56322e7d

login card sizing fixed

---

src/components/CourseView.tsx
src/components/Sidebar.tsx

- 1 Made the show content button and breadcrumb sticky
Resolves #1472 
https://github.com/user-attachments/assets/797bf5c3-f5eb-4bc2-a781-0c37de1480a0

Made the show content button and breadcrumb sticky

---

src/app/api/admin/services/externalLogin/route.ts

PR Fixes:
- Mitigate potential timing attacks
- Reduce excessive data exposure
- Implement robust input validation using Zod
- Standardize error messages to prevent user enumeration
- Improve error handling and logging
Resolves #1416 
Description:
This pull request addresses the security vulnerabilities identified in our external Login API endpoint. The following improvements have been implemented:
1. Timing attack mitigation: Implemented a constant-time comparison for non-existent users to prevent timing-based enumeration attacks.
2. Data exposure reduction: Limited the user and course data returned in the API response to only necessary fields, preventing exposure of sensitive information.
3. Input validation: Integrated Zod for robust input validation, ensuring that email and password …

bug: Security vulnerabilities in external Login API endpoint

---

src/app/layout.tsx
src/components/OfflineNavigator.tsx

- An offline notification when the user is not connected to internet but tries to reach the web application.
- This will include Harkirat's image at the center conveying a message to user that user is not connected to internet.
This resolves issue #1527 which was assigned to me by @devsargam . 
- It will look like this once merged.

Enhancement : Offline notification added

---

src/app/certificate/page.tsx
src/components/Certificate.tsx

- 1 certificate visiblity
#Before: 
#After:

Fix issue with certificate visibility

---

package.json
pnpm-lock.yaml
src/components/search/SearchResults.tsx
src/components/search/VideoSearchCard.tsx

- 1 add tooltip on hover of video title
- 2 working for both the themes (dark, light)
Resolves #1550 
- [✅] I assure there is no similar/duplicate pull request regarding same issue
Demo Video
https://github.com/user-attachments/assets/0f6fda9c-1aa0-453a-8098-b6b75e06420a

feat: add tooltip on hover of video title (#1550)

---

src/components/VideoPlayer2.tsx

- 1 fixed ratio for lecture on full web page 
- 2
Resolves #1523  
https://github.com/user-attachments/assets/befdfd8c-a1d7-4fa3-b6fb-39b50e723097
###After Solving this issue
https://github.com/user-attachments/assets/6f419cbf-1395-472c-8f78-bdd3b723a022

make video fitted as screen

---

src/components/VideoPlayer2.tsx

Fixed the check for window

---

src/components/search/SearchResults.tsx

- 1 #1596 fix search result container overflow
https://github.com/user-attachments/assets/03057272-57bd-43b1-b3a4-4e69cc664c1c
Resolves #1596

fix/1596: search result container overflow fix

---

src/components/Sidebar.tsx

PR Fixes:
Fixed issue where checkboxes were rendered for Notion content types.
Prevented unnecessary backend requests for Notion checkboxes.
Resolves #1570
Screenshot:
Checklist before requesting a review

changes: removed checkbox for notes

---

src/components/Sidebar.tsx

fix: small fixes

---

src/app/invalidsession/page.tsx
src/middleware.ts

feat: add followups

---

src/middleware.ts

middleware fixes

---

src/components/Sidebar.tsx

PR fixes the title in the side bar
Before Fix:
After Fix:

fixes title in sidebar

---

src/app/bounty/page.tsx
src/components/PaymentDropdown.tsx

| **Before**                                                                                                 | **After**                                                                                                  |
|----------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|
| <img width="846" alt="Screenshot 2024-12-09 at 8 10 07 PM" src="https://github.com/user-attachments/assets/25f723be-044f-42f5-a8f0-ddf190d7e460"> | <img width="847" alt="Screenshot 2024-12-09 at 8 11 48 PM" src="https://github.com/user-attachments/assets/c7ea2946-5540-406c-bce7-284f56899512"> |
---

fixed layout issues on bounty page

---

src/hooks/useCertGen.ts

- 1 Fixed the infinite loop issue in the "verify certificate request."
- 2 By removing the unnecessary certificateDetails from the dependancy array
Resolves #1690

fix: infinite certificate req

---

src/components/VideoPlayer2.tsx

- Removes the subtitiles from the video

fix: remove subtitles from video player

---

src/components/Sidebar.tsx

- 1 Ensure the bookmark button stays at the right side corner of the div even if the title content is less.
- 2 Makes UI look appropriate.
Resolves #1732

Modify sidebar content UI 

---

package.json
pnpm-lock.yaml
src/app/globals.css
src/components/VideoPlayer2.tsx

- Added zoom functionality to the video player for mobile devices
- Users can now zoom in/out using pinch gestures in fullscreen mode
- Added smooth panning when zoomed in
- Shows zoom level indicator (1x to 3x)
- Added auto-reset when exiting fullscreen

feat(video): add mobile pinch-to-zoom support
